### PR TITLE
Add Lifecycle Management support to the aws.s3.Bucket actor.

### PR DESCRIPTION
**Pull request by diranged**
This adds full management (configuring, deleting and updating) of the S3
bucket lifecycle policies. As many policies can be defined as needed,
and they are all schema-checked as much as possible to ensure fast
detection of invalid policies.

### CODE REVIEW

**Comment by diranged** [comment]
Tests coming .. but here's an example output:

# Deleting existing policies
```
(.venv)Matts-MacBook-2:kingpin diranged$ python kingpin/bin/deploy.py  --color --script s3.yaml
15:54:33   INFO      Rehearsing... Break a leg!
15:54:33   INFO      [DRY: Kingpin] Preparing actors from s3.yaml
15:54:33   INFO      [DRY: S3 Bucket mwise-test] Ensuring that s3://mwise-test is present
15:54:34   WARNING   [DRY: S3 Bucket mwise-test] Would have deleted the existing lifecycle configuration.
15:54:34   INFO      Rehearsal OK! Performing!
15:54:34   INFO      [Kingpin] Preparing actors from s3.yaml
15:54:34   INFO      
15:54:34   WARNING   Lights, camera ... action!
15:54:34   INFO      
15:54:34   INFO      [S3 Bucket mwise-test] Ensuring that s3://mwise-test is present
15:54:35   INFO      [S3 Bucket mwise-test] Deleting the existing lifecycle configuration.
```

# Creating new policies
```
(.venv)Matts-MacBook-2:kingpin diranged$ python kingpin/bin/deploy.py  --color --script s3.yaml
15:54:44   INFO      Rehearsing... Break a leg!
15:54:44   INFO      [DRY: Kingpin] Preparing actors from s3.yaml
15:54:44   INFO      [DRY: S3 Bucket mwise-test] Ensuring that s3://mwise-test is present
15:54:46   WARNING   [DRY: S3 Bucket mwise-test] Would have pushed the following lifecycle configuration: [<Rule: test-with-expiration>, <Rule: test-with-transition>]
15:54:46   INFO      Rehearsal OK! Performing!
15:54:46   INFO      [Kingpin] Preparing actors from s3.yaml
15:54:46   INFO      
15:54:46   WARNING   Lights, camera ... action!
15:54:46   INFO      
15:54:46   INFO      [S3 Bucket mwise-test] Ensuring that s3://mwise-test is present
15:54:46   INFO      [S3 Bucket mwise-test] Updating the Bucket Lifecycle config
```

# Updating of the policy
```
(.venv)Matts-MacBook-2:kingpin diranged$ python kingpin/bin/deploy.py  --color --script s3.yaml
15:56:02   INFO      Rehearsing... Break a leg!
15:56:02   INFO      [DRY: Kingpin] Preparing actors from s3.yaml
15:56:02   INFO      [DRY: S3 Bucket mwise-test] Ensuring that s3://mwise-test is present
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Lifecycle configurations do not match. Updating.
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff: --- a
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff: +++ b
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff: [
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff: @@ -0,2 +0,2 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:  (u'LifecycleConfiguration', u''),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:  (u'py/object', u'boto.s3.lifecycle.Lifecycle'),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:  (
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:  @@ -0,1 +0,1 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:   u'py/seq',
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:    [
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:   @@ -0,1 +0,1 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:      [
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:    @@ -2,6 +2,6 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:     (u'prefix', u'/test_transition'),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:     (u'py/object', u'boto.s3.lifecycle.Rule'),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:     (u'status', u'Enabled'),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:        (
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:     @@ -0,1 +0,1 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:      u'transition',
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          [
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:      @@ -0,5 +0,5 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:       (u'current_transition_property', 1),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:       (u'py/object', u'boto.s3.lifecycle.Transitions'),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:            (
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:       @@ -0,1 +0,1 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:        u'py/seq',
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:              [
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:        @@ -0 +0 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:                [
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:         @@ -0,3 +0,3 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          (u'date', None),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:                  (
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          @@ -0,1 +0,1 @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:           u'days',
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          -30,
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          +45,
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          ),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          (u'py/object', u'boto.s3.lifecycle.Transition'),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:          (u'storage_class', u'STANDARD_IA'),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:         ],
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:        ],
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:       ),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:       (u'temp_date', None),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:       (u'temp_days', None),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:       (u'temp_storage_class', None),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:      @@  @@
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:      ],
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:     ),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:    ],
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:    [(u'Rule', u''), (u'expiration', [(u'date', None), (u'days', 30), (u'py/object', u'boto.s3.lifecycle.Expiration')]), (u'id', u'test-with-expiration'), (u'prefix', u'/test_expir'), (u'py/object', u'boto.s3.lifecycle.Rule'), (u'status', u'Enabled'), (u'transition', [(u'current_transition_property', 1), (u'py/object', u'boto.s3.lifecycle.Transitions'), (u'py/seq', []), (u'temp_date', None), (u'temp_days', None), (u'temp_storage_class', None), (u'transition_properties', 3)])],
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:   ],
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff:  ),
15:56:04   INFO      [DRY: S3 Bucket mwise-test] Diff: ]
15:56:04   WARNING   [DRY: S3 Bucket mwise-test] Would have pushed the following lifecycle configuration: [<Rule: test-with-expiration>, <Rule: test-with-transition>]
15:56:04   INFO      Rehearsal OK! Performing!
15:56:04   INFO      [Kingpin] Preparing actors from s3.yaml
15:56:04   INFO      
15:56:04   WARNING   Lights, camera ... action!
15:56:04   INFO      
15:56:04   INFO      [S3 Bucket mwise-test] Ensuring that s3://mwise-test is present
15:56:05   INFO      [S3 Bucket mwise-test] Lifecycle configurations do not match. Updating.
15:56:05   INFO      [S3 Bucket mwise-test] Diff: --- a
15:56:05   INFO      [S3 Bucket mwise-test] Diff: +++ b
15:56:05   INFO      [S3 Bucket mwise-test] Diff: [
15:56:05   INFO      [S3 Bucket mwise-test] Diff: @@ -0,2 +0,2 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:  (u'LifecycleConfiguration', u''),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:  (u'py/object', u'boto.s3.lifecycle.Lifecycle'),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:  (
15:56:05   INFO      [S3 Bucket mwise-test] Diff:  @@ -0,1 +0,1 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:   u'py/seq',
15:56:05   INFO      [S3 Bucket mwise-test] Diff:    [
15:56:05   INFO      [S3 Bucket mwise-test] Diff:   @@ -0,1 +0,1 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:      [
15:56:05   INFO      [S3 Bucket mwise-test] Diff:    @@ -2,6 +2,6 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:     (u'prefix', u'/test_transition'),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:     (u'py/object', u'boto.s3.lifecycle.Rule'),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:     (u'status', u'Enabled'),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:        (
15:56:05   INFO      [S3 Bucket mwise-test] Diff:     @@ -0,1 +0,1 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:      u'transition',
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          [
15:56:05   INFO      [S3 Bucket mwise-test] Diff:      @@ -0,5 +0,5 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:       (u'current_transition_property', 1),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:       (u'py/object', u'boto.s3.lifecycle.Transitions'),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:            (
15:56:05   INFO      [S3 Bucket mwise-test] Diff:       @@ -0,1 +0,1 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:        u'py/seq',
15:56:05   INFO      [S3 Bucket mwise-test] Diff:              [
15:56:05   INFO      [S3 Bucket mwise-test] Diff:        @@ -0 +0 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:                [
15:56:05   INFO      [S3 Bucket mwise-test] Diff:         @@ -0,3 +0,3 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          (u'date', None),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:                  (
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          @@ -0,1 +0,1 @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:           u'days',
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          -30,
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          +45,
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          ),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          (u'py/object', u'boto.s3.lifecycle.Transition'),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:          (u'storage_class', u'STANDARD_IA'),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:         ],
15:56:05   INFO      [S3 Bucket mwise-test] Diff:        ],
15:56:05   INFO      [S3 Bucket mwise-test] Diff:       ),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:       (u'temp_date', None),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:       (u'temp_days', None),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:       (u'temp_storage_class', None),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:      @@  @@
15:56:05   INFO      [S3 Bucket mwise-test] Diff:      ],
15:56:05   INFO      [S3 Bucket mwise-test] Diff:     ),
15:56:05   INFO      [S3 Bucket mwise-test] Diff:    ],
15:56:05   INFO      [S3 Bucket mwise-test] Diff:    [(u'Rule', u''), (u'expiration', [(u'date', None), (u'days', 30), (u'py/object', u'boto.s3.lifecycle.Expiration')]), (u'id', u'test-with-expiration'), (u'prefix', u'/test_expir'), (u'py/object', u'boto.s3.lifecycle.Rule'), (u'status', u'Enabled'), (u'transition', [(u'current_transition_property', 1), (u'py/object', u'boto.s3.lifecycle.Transitions'), (u'py/seq', []), (u'temp_date', None), (u'temp_days', None), (u'temp_storage_class', None), (u'transition_properties', 3)])],
15:56:05   INFO      [S3 Bucket mwise-test] Diff:   ],
15:56:05   INFO      [S3 Bucket mwise-test] Diff:  ),
15:56:05   INFO      [S3 Bucket mwise-test] Diff: ]
15:56:05   INFO      [S3 Bucket mwise-test] Updating the Bucket Lifecycle config
```

**Comment by diranged** [comment]
@mikhail, updated the PR with full tests.. ran the integration tests locally an they work too:

```
(.venv)Matts-MacBook-2:kingpin diranged$ nosetests -vv --include=integration --attr=integration kingpin/actors/aws/test/integration_s3.py
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.config: INFO: Including tests matching ['integration']
integration_01_create_bucket (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_02a_set_bucket_policy (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_02b_delete_bucket_policy (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_03a_enable_versioning (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_03b_disable_versioning (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_04a_enable_lifecycle_management (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_04b_update_lifecycle_management (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_04c_disable_lifecycle_management (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok
integration_09_delete_bucket (kingpin.actors.aws.test.integration_s3.IntegrationS3) ... ok

----------------------------------------------------------------------
Ran 9 tests in 37.372s
```

**Comment by diranged** [comment]
Docs render properly, including intersphinx links to the boto docs:
image
image

**Comment by mikhail** [comment]
Nice! merge it!

**Pull request merged**
