### PR TITLE
Prep for v0.3.0 release

### PR DESCRIPTION
**Pull request by diranged**
@simin please review..

### CODE REVIEW

**Comment by diranged** [comment]
Specifically, let me know if I've missed any good things to document in the WHATSNEW.md file.

**Comment by siminm** [comment]
Similar to Async concurrency limit we also released `RightScale.server_array.Execute` limit. Same concept but applied to ServerArrays spcifically

**Comment by diranged** [comment]
@siminm, i updated the whatsnew doc...

**Comment by siminm** [comment]
:+1:

**Pull request merged**
